version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "08:00"
      timezone: "Asia/Tehran"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
    groups:
      vue:
        patterns:
          - "vue*"
          - "@vue*"
      eslint:
        patterns:
          - "eslint*"
          - "@eslint/*"
      typescript:
        patterns:
          - "typescript"
          - "vue-tsc"
    ignore:
      - dependency-name: "@types/node"
        versions: ["23.x", "24.x"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
